config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :vehicles
  resources :transfers
  resources :users
  resources :vehicles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/cpf_cnpj_validator.rb
class CpfCnpjValidator < ActiveModel::Validator
  require "cpf_cnpj"
  
  def validate(record)
    unless CPF.valid?(record.cpf_cnpj) or CNPJ.valid?(record.cpf_cnpj)
      record.errors[:base] << "CPF/CNPJ inválido!"
    end
  end
end

app/models/transfer.rb
# == Schema Information
#
# Table name: transfers
#
#  id         :bigint           not null, primary key
#  seller_id  :bigint
#  buyer_id   :bigint
#  vehicle_id :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Transfer < ApplicationRecord
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer,  class_name: 'User'
  belongs_to :vehicle

  validates :seller, :buyer, :vehicle, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  name                   :string
#  cpf_cnpj               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
  
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  has_many :vehicles, dependent: :destroy

  validates :name, :cpf_cnpj, presence: true
  validates :cpf_cnpj, uniqueness: {message: "CPF/CNPJ já existe!"},  allow_blank: true
  validates_with CpfCnpjValidator, fields: [:cpf_cnpj]
end

app/models/vehicle.rb
# == Schema Information
#
# Table name: vehicles
#
#  id         :bigint           not null, primary key
#  board      :string
#  renavam    :string
#  model      :string
#  year       :string
#  user_id    :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vehicle < ApplicationRecord
  belongs_to :user

  validates :board, :renavam, :model, :year, :user, presence: true

  def transferir_propriedade(novo_proprietario)
    self.user = novo_proprietario
    self.save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :cpf_cnpj)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :cpf_cnpj)}
  end

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :set_transfer, only: []

  def index
    @transfers = Transfer.all.order(created_at: :asc)
  end

  def new
    @transfer = Transfer.new
    @vehicle  = Vehicle.find(params[:veiculo])
  end

  def create
    @vehicle  = Vehicle.find_by(board: params[:transfer][:vehicle])
    @transfer = Transfer.new(vehicle_id: @vehicle.id, 
                             seller_id: params[:transfer][:seller_id],
                             buyer_id: params[:transfer][:buyer_id])

    @vehicle.transferir_propriedade(User.find(params[:transfer][:buyer_id]))

    respond_to do |format|
      if @transfer.save
        flash[:success] = 'Transferência realizada com sucesso!'
        format.js { redirect_to vehicles_path }
      else
        format.js { render :new }
      end
    end
  end

  private

  def transfer_params
    params.require(:transfer).permit(:seller_id, :buyer_id, :vehicle)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save!
        flash[:success] = 'Pessoa cadastrada com sucesso!'
        format.js { redirect_to users_path }
      else
        format.js { render :new }
      end
    end
  rescue => e
    respond_to do |format|
      flash.now[:error] = e
      format.js { render :new }
    end
  end

  def edit 
  end

  def update
    respond_to do |format|
      if @user.update!(user_params)
        flash[:success] = 'Pessoa atualizada com sucesso!'
        format.js { redirect_to users_path }
      else
        flash.now[:error] = e
        format.js { render :edit }
      end
    end
  rescue => e
    respond_to do |format|
      flash.now[:error] = e
      format.js { render :edit }
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = 'Pessoa deletada com sucesso!'
    redirect_to users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :cpf_cnpj, :email, :password, :password_confirmation)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:edit, :update, :destroy]

  def index
    @vehicles = Vehicle.all
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        flash[:success] = 'Veículo cadastrado com sucesso!'
        format.js { redirect_to vehicles_path }
      else
        format.js { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        flash[:success] = 'Veículo atualizado com sucesso!'
        format.js { redirect_to vehicles_path }
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @vehicle.destroy
    flash[:notice] = 'Veículo deletado com sucesso!'
    redirect_to vehicles_path
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:board, :renavam, :model, :year, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice'  then "alert alert-info alert-dismissible fade show"
      when 'success' then "alert alert-success alert-dismissible fade show"
      when 'error'   then "alert alert-danger alert-dismissible fade show"
      when 'alert'   then "alert alert-warning alert-dismissible fade show"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/home/index.html.haml
.jumbotron.jumbotron-fluid
  .container
    %h1.display-4 Mondrian
    %p.lead Transferência de Veículos

app/views/layouts/_flash_message.html.haml
- flash.each do |key, value|
	%div{:class => "#{flash_class(key)}"}
		= value
		%button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
			%span{"aria-hidden" => "true"} ×

app/views/layouts/_modal.html.haml
#modal-window.modal.fade.bd-example-modal-lg{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button'}
          %span{'aria-hidden' => 'true'} ×
      .modal-body
        Aguarde...

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    %a.navbar-brand{:href => "#"} Navbar
    %button.navbar-toggler{"aria-controls" => "navbarTogglerDemo02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarTogglerDemo02", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarTogglerDemo02.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto.mt-2.mt-lg-0
        %li.nav-item.active
          = link_to root_path, class: 'nav-link' do
            %span.sr-only (current)
            Início
        %li.nav-item
          = link_to 'Transferências', transfers_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Veículos', vehicles_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Pessoas', users_path, class: 'nav-link'
      %ul.navbar-nav
        .text-secondary.mr-2= "Usuário: #{current_user.email}"
        = link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-dark btn-sm'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title Mondrian-Test
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container
      .my-5
        = render 'layouts/flash_message'
        = yield
        = render 'layouts/modal'

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title Mondrian-Test | Login
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'devise', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.text-center
    = yield

app/views/transfers/_form.html.haml
= simple_form_for @transfer, remote: true do |f|
  .form-row
    .col
      = f.input :vehicle, label: 'Veículo', input_html: { value: @vehicle.board, readonly: true }
    .col
      = f.association :buyer, label: 'Comprador', collection: User.where.not(id: @vehicle.user.id), prompt: "Selecione o comprador"
  
  = f.input :seller_id, as: :hidden, input_html: {value: @vehicle.user.id}
  .d-flex.justify-content-end
    %button.btn.btn-dark.btn_transferir{type: 'submit'} Salvar

app/views/transfers/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h2
    %i.fas.fa-car-side
    Transferências

- if @transfers.present?
  %hr.mb-5
  .table-responsive
    %table.table.table-hover.table-striped.table-bordered
      %thead
        %tr.text-center
          %th{:scope => "col"} #
          %th{:scope => "col"} Vendedor
          %th{:scope => "col"} Comprador
          %th{:scope => "col"} Veículo
          %th{:scope => "col"} Data
      %tbody
        - @transfers.each_with_index do |transf, index|
          %tr.text-center
            %th{:scope => "row"}=index+1
            %td=transf.seller.name
            %td=transf.buyer.name
            %td=transf.vehicle.board   
            %td=transf.created_at.strftime("%d/%m/%Y - %H:%M")

app/views/transfers/new.html.haml
= render 'form'

app/views/transfers/new.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'transfers/new.html.haml')}");
  modal.find('.modal-title').html("Transferindo Vaículo");
  modal.modal();

app/views/users/_form.html.haml
= simple_form_for @user, remote: true do |f|
  = render 'layouts/flash_message'
  .form-group
    = f.input :name, placeholder: 'Nome completo', label: 'Nome'
  .form-row
    .col
      = f.input :password, placeholder: '*****', label: 'Senha'
    .col
      = f.input :password_confirmation, placeholder: '*****', label: 'Confirmação de senha'
  .form-row
    .col 
      = f.input :email, placeholder: 'Email'
    .col 
      = f.input :cpf_cnpj, placeholder: 'Apenas Números', label: 'CPF/CNPJ'

  .d-flex.justify-content-end
    %button.btn.btn-dark{type: 'submi'} Salvar

app/views/users/edit.html.haml
= render 'form'

app/views/users/edit.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'users/edit.html.haml')}");
  modal.find('.modal-title').html("Editar Pessoa");
  modal.modal();

app/views/users/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h2
    %i.fas.fa-users
    Pessoas

  = link_to new_user_path, remote: true, class: 'btn btn-outline-primary btn-sm' do
    %i.fas.fa-plus
    Adicionar

%hr.mb-5
.table-responsive
  %table.table.table-hover.table-striped.table-bordered
    %thead
      %tr.text-center
        %th{:scope => "col"} #
        %th{:scope => "col"} Nome
        %th{:scope => "col"} Email
        %th{:scope => "col"} CPF/CNPJ
        %th{:scope => "col"}
          %i.fa.fa-cogs
    %tbody
      - @users.each_with_index do |user, index|
        %tr.text-center
          %th{:scope => "row"}=index+1
          %td=user.name
          %td=user.email
          %td=user.cpf_cnpj
          %td 
            = link_to edit_user_path(user), remote: true, class: 'btn btn-sm btn-outline-dark', title: 'Editar' do
              %i.fas.fa-edit
            - unless user.eql?(current_user)
              = link_to user_path(user), method: :delete, data: {confirm: "Apagar Pessoa #{user.name} ?"}, 
                class: 'btn btn-outline-dark btn-sm mx-1', title: 'Apagar' do
                %i.fas.fa-trash

app/views/users/new.html.haml
= render 'form'

app/views/users/new.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'users/new.html.haml')}");
  modal.find('.modal-title').html("Nova Pessoa");
  modal.modal();

app/views/vehicles/_form.html.haml
= simple_form_for @vehicle, remote: true do |f|
  .form-row
    .col
      = f.input :board, placeholder: 'Placa do veículo', label: 'Placa'
    .col
      = f.input :renavam, placeholder: 'Apenas números'
  .form-row
    .col
      = f.input :model, placeholder: 'Ex: Gol 1.8 G5', label: 'Modelo'
    .col
      = f.input :year, placeholder: 'Ano de fabricação', label: 'Ano'
  .form-group
    = f.association :user, label_method: :name, value_method: :id, include_blank: 'Escolha o proprietário'

  .d-flex.justify-content-end
    %button.btn.btn-dark{type: 'submi'} Salvar

app/views/vehicles/edit.html.haml
= render 'form'

app/views/vehicles/edit.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'vehicles/edit.html.haml')}");
  modal.find('.modal-title').html("Editar Veículo");
  modal.modal();

app/views/vehicles/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h2
    %i.fas.fa-car-side
    Veículos

  = link_to new_vehicle_path, remote: true, class: 'btn btn-outline-primary btn-sm' do
    %i.fas.fa-plus
    Adicionar

- if @vehicles.present?
  %hr.mb-5
  .table-responsive
    %table.table.table-hover.table-striped.table-bordered
      %thead
        %tr.text-center
          %th{:scope => "col"} #
          %th{:scope => "col"} Placa
          %th{:scope => "col"} Renavam
          %th{:scope => "col"} Modelo
          %th{:scope => "col"} Ano Fabricação
          %th{:scope => "col"} Proprietário
          %th{:scope => "col"}
            %i.fa.fa-cogs
      %tbody
        - @vehicles.each_with_index do |veiculo, index|
          %tr.text-center
            %th{:scope => "row"}=index+1
            %td=veiculo.board.upcase
            %td=veiculo.renavam
            %td=veiculo.model
            %td=veiculo.year
            %td=veiculo.user.name
            %td 
              = link_to edit_vehicle_path(veiculo), remote: true, class: 'btn btn-sm btn-outline-dark', title: 'Editar' do
                %i.fas.fa-edit

              = link_to vehicle_path(veiculo), method: :delete, data: {confirm: "Apagar Veículo #{veiculo.board} ?"}, 
                class: 'btn btn-outline-dark btn-sm mx-1', title: 'Apagar' do
                %i.fas.fa-trash
              
              = link_to new_transfer_path(veiculo: veiculo), remote: true, class: 'btn btn-sm btn-outline-dark', title: 'Transferir veículo' do
                %i.fas.fa-exchange-alt

app/views/vehicles/new.html.haml
= render 'form'

app/views/vehicles/new.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'vehicles/new.html.haml')}");
  modal.find('.modal-title').html("Nova Veículo");
  modal.modal();